#!/bin/bash
set -e

# Default database and user names
: ${JIRA_DB:='jira'}
: ${JIRA_DB_USER:='jira_cntr'}
: ${CONFLUENCE_DB:='confluence'}
: ${CONFLUENCE_DB_USER:='confluence_cntr'}
: ${BITBUCKET_DB:='bitbucket'}
: ${BITBUCKET_DB_USER:='bitbucket_cntr'}
: ${BAMBOO_DB:='bamboo'}
: ${BAMBOO_DB_USER:='bamboo_cntr'}

# Check if secrets have been provided
: ${JIRA_DB_PASSWORD?'Missing JIRA_DB_PASSWORD'}
: ${CONFLUENCE_DB_PASSWORD?'Missing CONFLUENCE_DB_PASSWORD'}
: ${BITBUCKET_DB_PASSWORD?'Missing BITBUCKET_DB_PASSWORD'}
: ${BAMBOO_DB_PASSWORD?'Missing BAMBOO_DB_PASSWORD'}

# Use default postgres user if needed
: ${POSTGRES_USER:=postgres} 

# Create databases and users
psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER <<-EOSQL
    CREATE USER $JIRA_DB_USER WITH PASSWORD '$JIRA_DB_PASSWORD';
    CREATE USER $CONFLUENCE_DB_USER WITH PASSWORD '$CONFLUENCE_DB_PASSWORD';
    CREATE USER $BITBUCKET_DB_USER WITH PASSWORD '$BITBUCKET_DB_PASSWORD';
    CREATE USER $BAMBOO_DB_USER WITH PASSWORD '$BAMBOO_DB_PASSWORD'; 

    CREATE DATABASE $JIRA_DB WITH OWNER $JIRA_DB_USER ENCODING 'UTF-8' LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0;
    CREATE DATABASE $CONFLUENCE_DB WITH OWNER $CONFLUENCE_DB_USER ENCODING 'UTF-8' LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0;
    CREATE DATABASE $BITBUCKET_DB WITH OWNER $BITBUCKET_DB_USER ENCODING 'UTF-8' LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0;
    CREATE DATABASE $BAMBOO_DB WITH OWNER $BAMBOO_DB_USER ENCODING 'UTF-8' LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0;
EOSQL
